### ISSUE TITLE
Missing TS.REVRANGE and TS.MREVRANGE commands

### ISSUE THREAD

**Issue by cjdsellers** [RedisTimeSeries/NRedisTimeSeries#22]
I found that these commands are not available via any methods in the TimeSeriesClient. I have a use case whereby I need to retrieve the latest data with a count specified and the reverse command achieves this.

I've implemented my own extension method to get around the issue however I thought I would flag this as I know you're preparing a new release. I could also open a PR.

**Comment by gkorland** [comment]
@cjdsellers thanks for the feedback! a PR will be more than welcome

**Comment by cjdsellers** [comment]
Are you OK with me opening a pull requesting directly on master?

**Comment by cjdsellers** [comment]
I believe this issue is closed now. Out of interest what is the release schedule?

**Comment by DvirDukhan** [comment]
@cjdsellers 
release schedule of this client library?
Unfortunately is falls under "best-effort" on my behalf. Although this is a nice small project, it is not one of my main projects, so I'll try to do my best here.

**Comment by cjdsellers** [comment]
Ok, I understand. Thanks for following up.

**Comment by DvirDukhan** [comment]
closed by #23
