### ISSUE TITLE
Pipelining of TS.ADD

### ISSUE THREAD

**Issue by lhh31** [RedisTimeSeries/NRedisTimeSeries#39]
**Version**

1.3.0

**Issue**

Does the TS.ADD implement a pipelining mechanism to allow for higher throughput? Is using the Async mechanism analogous to pipelining, if so are there any examples on how to implement pipelining correctly?

**Comment by gkorland** [comment]
TS has an even more optimized way to push data see `MADD`.
You can see an example here: https://github.com/RedisTimeSeries/NRedisTimeSeries/blob/master/NRedisTimeSeries.Test/TestAPI/TestMAddAsync.cs

**Comment by AvitalFineRedis** [comment]
Also, you can use the asynchronous methods for pipelining your requests :-)
