### ISSUE TITLE
Add zrevrangebyts ?

### ISSUE THREAD

**Issue by Shackman287** [RedisTimeSeries/NRedisTimeSeries#59]
When using sorted sets for time series I use zrevrangebyscore to find the latest element prior to a given timestamp. See the below example. It seems I cannot perform a similar nearest-neighbour look up with TS.RANGE, since the min and max values must match existing keys exactly.  Is there a way to find the nearest-neighbour with TS.RANGE? or would a TS.zrangebyts need to be added? I'm sure this kind of usage is common and would be a great addition to this phenomenal library.

 ZADD mySortedSet 1.1 100
 ZADD mySortedSet 1.2 200
 ZADD mySortedSet 1.3 300
ZADD mySortedSet 1.4 400
ZADD mySortedSet 1.5 500

 zrevrangebyscore mySortedSet 1.25 -inf LIMIT 0 1
1) "200"
 zrevrangebyscore mySortedSet 1.35 -inf LIMIT 0 1
1) "300"
 zrevrangebyscore mySortedSet 1.42 -inf LIMIT 0 1

**Comment by gkorland** [comment]
First I guess you meant "300" and "400"
```
127.0.0.1:6379> zrevrangebyscore mySortedSet 1.35 -inf LIMIT 0 1
1) "300"
127.0.0.1:6379> zrevrangebyscore mySortedSet 1.42 -inf LIMIT 0 1
1) "400"
```


As for RedisTimeSeries you can also achieve it easily.
e.g.
```
127.0.0.1:6379> TS.ADD myTS 110 100
(integer) 110
127.0.0.1:6379> TS.ADD myTS 120 200
(integer) 120
127.0.0.1:6379> TS.ADD myTS 130 300
(integer) 130
127.0.0.1:6379> TS.ADD myTS 140 400
(integer) 140
127.0.0.1:6379> TS.ADD myTS 150 500
(integer) 150


127.0.0.1:6379> TS.REVRANGE myTS 0 142 COUNT 1
1) 1) (integer) 140
   2) 400
127.0.0.1:6379> TS.REVRANGE myTS 0 130 COUNT 1
1) 1) (integer) 130
   2) 300
```

**Comment by Shackman287** [comment]
This is extremely helpful and you have added my question. I'm not sure why this didn't work the first time I used REVRANGE. Great library and look forward to its continued development.
